'use strict';

function createNodeState() {
    var SELECT_STATE = {
        DEFAULT: 'CLICK THE CAR!',
        DRAGGABLE: 'MOVE THE POINTER TO DRAG THE CAR!',
        SCALABLE_LENGTH: 'MOVE THE POINTER TO MAKE THE CAR SHORTER OR LONGER',
        SCALABLE_WIDTH: 'MOVE THE POINTER TO MAKE THE CAR WIDER OR NARROWER',
        MOUSE_DOWN: 'CAR_STATE_MOUSE_DOWN',
        ROTATABLE: 'MOVE THE POINTER TO ROTATE THE CAR',
        WHEEL: 'MOVE THE POINTER TO CHANGE AXLE LENGTH'
    };

    var HOVER_STATE = {
        DEFAULT: 'MOUSE OVER THE CAR FOR OPTIONS!',
        HOVER_DRAG: 'CLICK TO DRAG  THE CAR AROUND!',
        HOVER_SCALE: 'CLICK TO RESIZE THE CAR!',
        HOVER_ROTATE: 'CLICK TO ROTATE',
        HOVER_WHEEL: 'CLICK TO CHANGE AXLE LENGTH'
    }

    return {
        SELECT_STATE: SELECT_STATE,
        HOVER_STATE: HOVER_STATE
    };
}
